# Generated by Django 5.0.4 on 2024-05-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_mesas', models.CharField(max_length=45, null=True)),
                ('capacidad_mesas', models.CharField(max_length=45, null=True)),
                ('disponibilidad', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('img_restaurante', models.CharField(max_length=45, null=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('fecha_disponibilidad', models.CharField(max_length=45)),
                ('n_mesas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.CharField(max_length=45, null=True)),
                ('hora_llegada', models.CharField(max_length=45, null=True)),
                ('mesas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesas')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.metodopago')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mesas',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante'),
        ),
    ]
