# Generated by Django 5.0.4 on 2024-05-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.CharField(max_length=45)),
                ('fecha_salida', models.CharField(max_length=45)),
                ('hora_llegada', models.CharField(max_length=45)),
                ('hora_salida', models.CharField(max_length=45)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.metodopago')),
                ('reserva_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.reservahotel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=45)),
                ('cedula', models.CharField(max_length=45, unique=True)),
                ('tel', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioHasReservaHotel',
            fields=[
                ('reserva_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuario.reservahotel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
