# Generated by Django 5.0.4 on 2024-05-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_habitaciones_reserva_hotel'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahotel',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.habitaciones'),
        ),
    ]
