# Generated by Django 5.0.4 on 2024-05-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_img_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ofertas',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
