# Generated by Django 5.0.4 on 2024-05-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_ofertas_id_habitacion_ofertas_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='reserva_hotel',
        ),
    ]
