# Generated by Django 5.0.4 on 2024-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_habitaciones_reserva_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='fecha_finalizacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
