# Generated by Django 5.0.4 on 2024-05-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_ofertas_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='ofertascol',
            new_name='descripcion_oferta',
        ),
    ]
