# Generated by Django 5.0.4 on 2024-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='img_plan',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
